languages = {
    "English": "en",
    "Russian": "ru",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Polish": "pl",
    "Dutch": "nl",
    "Vietnamese": "vi",
    "Turkish": "tr",
    "Swedish": "sv",
    "Indonesian": "id",
    "Romanian": "ro",
    "Czech": "cs",
    "Mandarin Chinese": "zh",
    "Hungarian": "hu",
    "Japanese": "ja",
    "Thai": "th",
    "Finnish": "fi",
    "Persian": "fa",
    "Ukrainian": "uk",
    "Danish": "da",
    "Greek": "el",
    "Norwegian": "no",
    "Bulgarian": "bg",
    "Slovak": "sk",
    "Korean": "ko",
    "Arabic": "ar",
    "Lithuanian": "lt",
    "Catalan": "ca",
    "Slovenian": "sl",
    "Hebrew": "he",
    "Estonian": "et",
    "Latvian": "lv",
    "Hindi": "hi",
    "Albanian": "sq",
    "Malay": "ms",
    "Azerbaijani": "az",
    "Serbian": "sr",
    "Tamil": "ta",
    "Croatian": "hr",
    "Kazakh": "kk",
    "Icelandic": "is",
    "Malayalam": "ml",
    "Marathi": "mr",
    "Telugu": "te",
    "Afrikaans": "af",
    "Galician": "gl",
    "Filipino": "fil",
    "Belarusian": "be",
    "Macedonian": "mk",
    "Basque": "eu",
    "Bengali": "bn",
    "Georgian": "ka",
    "Mongolian": "mn",
    "Bosnian": "bs",
    "Uzbek": "uz",
    "Urdu": "ur",
    "Swahili": "sw",
    "Cantonese": "yue",
    "Nepali": "ne",
    "Kannada": "kn",
    "Kara-Kalpak": "kaa",
    "Gujarati": "gu",
    "Sinhala": "si",
    "Welsh": "cy",
    "Esperanto": "eo",
    "Latin": "la",
    "Armenian": "hy",
    "Kyrghyz": "ky",
    "Tajik": "tg",
    "Irish": "ga",
    "Maltese": "mt",
    "Myanmar (Burmese)": "my",
    "Khmer": "km",
    "Tatar": "tt",
    "Somali": "so",
    "Kurdish (Kurmanji)": "ku",
    "Pashto": "ps",
    "Punjabi": "pa",
    "Kinyarwanda": "rw",
    "Lao": "lo",
    "Hausa": "ha",
    "Dhivehi": "dv",
    "W. Frisian": "fy",
    "Luxembourgish": "lb",
    "Kurdish (Sorani)": "ckb",
    "Malagasy": "mg",
    "Scottish Gaelic": "gd",
    "Amharic": "am",
    "Uyghur": "ug",
    "Haitian Creole": "ht",
    "Ancient Greek": "grc",
    "Hmong": "hmn",
    "Sindhi": "sd",
    "Javanese": "jv",
    "Maori": "mi",
    "Turkmen": "tk",
    "Cebuano": "ceb",
    "Yiddish": "yi",
    "Bashkir": "ba",
    "Faroese": "fo",
    "Odia (Oriya)": "or",
    "Xhosa": "xh",
    "Sundanese": "su",
    "Kalaallisut": "kl",
    "Chichewa": "ny",
    "Samoan": "sm",
    "Shona": "sn",
    "Corsican": "co",
    "Zulu": "zu",
    "Igbo": "ig",
    "Yoruba": "yo",
    "Papiamento": "pap",
    "Sesotho": "st",
    "Hawaiian": "haw",
    "Assamese": "as",
    "Occitan": "oc",
    "Chuvash": "cv",
    "Mizo": "lus",
    "Tetum": "tet",
    "Swiss German": "gsw",
    "Yakut": "sah",
    "Breton": "br",
    "Romansh": "rm",
    "Sanskrit": "sa",
    "Tibetan": "bo",
    "Oromo": "om",
    "N. Sami": "se",
    "Chechen": "ce",
    "Hakha Chin": "cnh",
    "Ilocano": "ilo",
    "Hiligaynon": "hil",
    "Udmurt": "udm",
    "Ossetian": "os",
    "Luganda": "lg",
    "Tigrinya": "ti",
    "Venetian": "vec",
    "Tsonga": "ts",
    "Tuvinian": "tyv",
    "Kabardian": "kbd",
    "Ewe": "ee",
    "Iban": "iba",
    "Avar": "av",
    "Khasi": "kha",
    "Tonga (Tonga Islands)": "to",
    "Tswana": "tn",
    "Sepedi": "nso",
    "Fijian": "fj",
    "Zaza": "zza",
    "Twi": "ak",
    "Adangme": "ada",
    "Querétaro Otomi": "otq",
    "Dzongkha": "dz",
    "Buryat": "bua",
    "Falam Chin": "cfm",
    "Lingala": "ln",
    "Meadow Mari": "chm",
    "Guarani": "gn",
    "Karachay-Balkar": "krc",
    "Walloon": "wa",
    "Fiji Hindi": "hif",
    "Yucateco": "yua",
    "Sranan Tongo": "srn",
    "Waray (Philippines)": "war",
    "Romani": "rom",
    "Central Bikol": "bik",
    "Pampanga": "pam",
    "Sango": "sg",
    "Luba-Katanga": "lu",
    "Adyghe": "ady",
    "Kabiyè": "kbp",
    "Syriac": "syr",
    "Latgalian": "ltg",
    "Erzya": "myv",
    "Isoko": "iso",
    "Kachin": "kac",
    "Bhojpuri": "bho",
    "Aymara": "ay",
    "Kumyk": "kum",
    "Quechua": "qu",
    "Zhuang": "za",
    "Pangasinan": "pag",
    "Guerrero Nahuatl": "ngu",
    "Venda": "ve",
    "Paite Chin": "pck",
    "Zapotec": "zap",
    "Tày": "tyz",
    "Huli": "hui",
    "Batak Toba": "bbc",
    "Tzotzil": "tzo",
    "Tiv": "tiv",
    "Kuanua": "ksd",
    "Goan Konkani": "gom",
    "Minangkabau": "min",
    "Old English": "ang",
    "E. Huasteca Nahuatl": "nhe",
    "E. Baluchi": "bgp",
    "Nzima": "nzi",
    "Nande": "nnb",
    "Navajo": "nv",
    "Noise": "zxx",
    "Baoulé": "bci",
    "Komi": "kv",
    "Newari": "new",
    "Dadibi": "mps",
    "S. Altai": "alt",
    "Motu": "meu",
    "Betawi": "bew",
    "Fon": "fon",
    "Inuktitut": "iu",
    "Ambulas": "abt",
    "Makhuwa-Meetto": "mgh",
    "Mon": "mnw",
    "Tuvalu": "tvl",
    "Dombe": "dov",
    "Klingon": "tlh",
    "Hiri Motu": "ho",
    "Cornish": "kw",
    "Hill Mari": "mrj",
    "Kedah Malay": "meo",
    "Crimean Tatar": "crh",
    "Matigsalug Manobo": "mbt",
    "N. Emberá": "emp",
    "Achinese": "ace",
    "Iu Mien": "ium",
    "Mam": "mam",
    "Ngäbere": "gym",
    "Maithili": "mai",
    "Seselwa Creole French": "crs",
    "Pohnpeian": "pon",
    "Umbu-Ungu": "ubu",
    "Fipa": "fip",
    "K’iche’": "quc",
    "Manx": "gv",
    "Kuanyama": "kj",
    "Batak Karo": "btx",
    "Bukiyip": "ape",
    "Chuukese": "chk",
    "Réunion Creole French": "rcf",
    "Shan": "shn",
    "Tzeltal": "tzh",
    "Moksha": "mdf",
    "Uma": "ppk",
    "Swati": "ss",
    "Gagauz": "gag",
    "Garifuna": "cab",
    "Krio": "kri",
    "Sena": "seh",
    "Ibibio": "ibb",
    "Ditammari": "tbz",
    "E. Bru": "bru",
    "Enga": "enq",
    "Acoli": "ach",
    "San Blas Kuna": "cuk",
    "Kimbundu": "kmb",
    "Wolof": "wo",
    "Kekchí": "kek",
    "Huallaga Huánuco Quechua": "qub",
    "Tabassaran": "tab",
    "Batak Simalungun": "bts",
    "Kosraean": "kos",
    "Rawa": "rwo",
    "Kaqchikel": "cak",
    "Mutu": "tuc",
    "Bulu": "bum",
    "Chokwe": "cjk",
    "Gilbertese": "gil",
    "Saterfriesisch": "stq",
    "Tausug": "tsg",
    "S. Bolivian Quechua": "quh",
    "Makasar": "mak",
    "Mapudungun": "arn",
    "Balinese": "ban",
    "Shuar": "jiv",
    "Epena": "sja",
    "Yapese": "yap",
    "Tulu": "tcy",
    "Tojolabal": "toj",
    "Termanu": "twu",
    "Kalmyk": "xal",
    "Guerrero Amuzgo": "amu",
    "Carpathian Romani": "rmc",
    "Huastec": "hus",
    "Nias": "nia",
    "Khakas": "kjh",
    "Bambara": "bm",
    "Guahibo": "guh",
    "Masai": "mas",
    "St Lucian Creole French": "acf",
    "Kadazan Dusun": "dtp",
    "S’gaw Karen": "ksw",
    "Belize Kriol English": "bzj",
    "Dinka": "din",
    "Zande": "zne",
    "Madurese": "mad",
    "Sabah Malay": "msi",
    "Magahi": "mag",
    "Kupang Malay": "mkn",
    "Kongo": "kg",
    "Lahu": "lhu",
    "Chamorro": "ch",
    "Imbabura H. Quichua": "qvi",
    "Marshallese": "mh",
    "E. Maroon Creole": "djk",
    "Susu": "sus",
    "Morisien": "mfe",
    "Saramaccan": "srm",
    "Dyula": "dyu",
    "Chol": "ctu",
    "E. Bolivian Guaraní": "gui",
    "Palauan": "pau",
    "Inga": "inb",
    "Bislama": "bi",
    "Meiteilon (Manipuri)": "mni",
    "Wayuu": "guc",
    "Jamaican Creole English": "jam",
    "Wolaytta": "wal",
    "Popti’": "jac",
    "Basa (Cameroon)": "bas",
    "Gorontalo": "gor",
    "Saraiki": "skr",
    "Nyungwe": "nyu",
    "Woun Meu": "noa",
    "Toraja-Sa’dan": "sda",
    "Guajajára": "gub",
    "Nogai": "nog",
    "Asháninka": "cni",
    "Teso": "teo",
    "Tandroy-Mahafaly Malagasy": "tdx",
    "Sangir": "sxn",
    "Rakhine": "rki",
    "South Ndebele": "nr",
    "Arpitan": "frp",
    "Alur": "alz",
    "E. Tamang": "taj",
    "N. Luri": "lrc",
    "Chopi": "cce",
    "Rundi": "rn",
    "Caribbean Javanese": "jvn",
    "Sabu": "hvn",
    "Ngaju": "nij",
    "Dawro": "dwr",
    "Izii": "izz",
    "Agusan Manobo": "msm",
    "Bokobaru": "bus",
    "Kituba (DRC)": "ktu",
    "Cherokee": "chr",
    "Central Mazahua": "maz",
    "Tz’utujil": "tzj",
    "Sunwar": "suz",
    "W. Kanjobal": "knj",
    "Bimoba": "bim",
    "Gulay": "gvl",
    "Boko (Benin)": "bqc",
    "Ticuna": "tca",
    "Pijin": "pis",
    "Parauk": "prk",
    "Lango (Uganda)": "laj",
    "Central Melanau": "mel",
    "Cañar H. Quichua": "qxr",
    "Nandi": "niq",
    "Akha": "ahk",
    "Shipibo-Conibo": "shp",
    "Chhattisgarhi": "hne",
    "Supyire Senoufo": "spp",
    "Komi-Permyak": "koi",
    "Kinaray-A": "krj",
    "Lambayeque Quechua": "quf",
    "S. Luri": "luz",
    "Aguaruna": "agr",
    "Tswa": "tsc",
    "Manggarai": "mqy",
    "Gofa": "gof",
    "Garhwali": "gbm",
    "Mískito": "miq",
    "Zarma": "dje",
    "Awadhi": "awa",
    "Kanauji": "bjj",
    "N. Pastaza Quichua": "qvz",
    "Surjapuri": "sjp",
    "Tetela": "tll",
    "Rajasthani": "raj",
    "Khmu": "kjg",
    "Banggai": "bgz",
    "Ayacucho Quechua": "quy",
    "Chavacano": "cbk",
    "Batak Angkola": "akb",
    "Ojibwa": "oj",
    "Keley-IKallahan": "ify",
    "Hassaniyya": "mey",
    "Kashmiri": "ks",
    "Chuj": "cac",
    "Bodo (India)": "brx",
    "S. Pastaza Quechua": "qup",
    "Sylheti": "syl",
    "Jambi Malay": "jax",
    "Fulfulde": "ff",
    "Tamazight (Tfng)": "ber",
    "Takestani": "tks",
    "Kok Borok": "trp",
    "Maranao": "mrw",
    "Adhola": "adh",
    "Simte": "smt",
    "Serer": "srr",
    "Maasina Fulfulde": "ffm",
    "Cajamarca Quechua": "qvc",
    "Mewari": "mtr",
    "Obolo": "ann",
    "Kara-Kalpak (Latn)": "kaa-Latn",
    "Afar": "aa",
    "Nimadi": "noe",
    "Nung (Viet Nam)": "nut",
    "Guyanese Creole English": "gyn",
    "Awa-Cuaiquer": "kwi",
    "Manado Malay": "xmm",
    "Masbatenyo": "msb",
    "Greek (Latn)": "el-Latn",
    "Dogri": "doi",
    "Muong": "mtq",
    "Darlong": "dln",
    "Cuyonon": "cyo",
    "Ambonese Malay": "abs",
    "Hindi (Latn)": "hi-Latn",
    "Chadian Arabic": "shu",
    "Yaqui": "yaq",
    "Nyoro": "nyo",
    "Chiga": "cgg",
    "Upper Saxon": "sxu",
    "Maguindanaon": "mdh",
    "Marwari (India)": "rwr",
    "Kangri": "xnr",
    "Musi": "mui",
    "Sakalava Malagasy": "skg",
    "Maay": "ymm",
    "Tedim Chin (Latn)": "ctd-Latn",
    "Libyan Arabic": "ayl",
    "Q’anjob’al": "kjb",
    "Rohingya (Latn)": "rhg-Latn",
    "N. Betsimisaraka Malagasy": "bmm",
    "San Pedro Amuzgos Amuzgo": "azg",
    "Kumaoni": "kfy",
    "Rinconada Bikol": "bto",
    "Japanese (Latn)": "ja-Latn",
    "Bangka": "mfb",
    "Russian (Latn)": "ru-Latn",
    "Central Tunebo": "tuf",
    "Chittagonian": "ctg",
    "Papuan Malay": "pmy",
    "Soga": "xog",
    "Telugu (Latn)": "te-Latn",
    "Tamazight (Latn)": "ber-Latn",
    "Male (Ethiopia)": "mdy",
    "Azerbaijani (Russia)": "az-RU",
    "Tamil (Latn)": "ta-Latn",
    "Caluyanun": "clu",
    "Talysh (Iran)": "tly-IR",
    "Ndonga": "ng",
    "S. Betsimisaraka Malagasy": "bzc",
    "Min Nan Chinese (Latn)": "nan-Latn-TW",
    "Malayalam (Latn)": "ml-Latn",
    "North Moluccan Malay": "max",
    "Arabic (Latn)": "ar-Latn",
    "Goan Konkani (Latn)": "gom-Latn",
    "Bulgarian (Latn)": "bg-Latn",
    "North Ndebele": "nd",
    "Youjiang Zhuang": "zyj",
    "Rangpuri": "rkt",
    "Kannada (Latn)": "kn-Latn",
    "Chinese (Latn)": "zh-Latn",
    "Greek (Cypress)": "el-CY",
    "Deccan": "dcc",
    "Haryanvi": "bgc",
    "Marwari": "mwr",
    "Tenggarong Kutai Malay": "vkt",
    "Cree (Latn)": "cr-Latn",
    "Sudanese Arabic": "apd-SD",
    "Torwali": "trw",
    "Bengali (Latn)": "bn-Latn",
    "Gujarati (Latn)": "gu-Latn",
    "Gujari": "gju",
    "Santali (Latn)": "sat-Latn",
    "Ndau": "ndc-ZW",
    "Khorasani Turkish (Latn)": "kmz-Latn",
    "Marathi (Latn)": "mr-Latn",
    "English (Cyrl)": "en-Cyrl",
    "English (Arab)": "en-Arab",
    "Malay (Jawi)": "ms-Arab",
    "Malay (Jawi, Brunei)": "ms-Arab-BN",
    "Bhili": "bhb-Gujr",
    "Lahnda Punjabi (PK)": "pa-Arab",
    "Sylheti (Latn)": "syl-Latn",
    "Fulah": "ff-Adlm",
    "Nigerian Pidgin": "pcm",
    "Tok Pisin": "tpi",
    "Kachi Koli": "gjk",
    "Bagheli": "bfy",
    "Surgujia": "sgj",
    "Nyankole": "nyn",
}
